### PR TITLE
Added JDK11 build support

### PR DESCRIPTION
**Pull request by m0mus**

### CODE REVIEW

**Comment by aguibert** [comment]
sorry, I just realized that this has a different target branch from #137  so I'm re-opening

**Comment by aguibert** [comment]
do we really need to dual-deliver to `master` and `EE4J_8` branches? Hopefully this will not be a long-term requirement of the project

**Comment by m0mus** [comment]
@aguibert When we've done with Jakarta EE 8 (soon) we will make EE4J_8 branch read only and work normally in master. Before that each EE4J_8 commit should be duplicated in master.

**Comment by m0mus** [comment]
@aguibert @lukasj I reflected changes I've done in EE4J_8 branch here. Please re-review.

**Pull request merged**
