### PR TITLE
GH-193 May adapter input / output be null?

### PR DESCRIPTION
**Pull request by mkarg**
Closing #193 with this PR: According to the concensus of the discussion in that issue, I'd like to propose two changes implemented by this PR:
* Correcting examples so those won't fail once `null` is passed.
* Enhancing JavaDocs to be absolutely clear about `null` handling.

### CODE REVIEW

**Comment by mkarg** [comment]
@rmannibucau @m0mus Review please. :-)

**Comment by rmannibucau** [comment]
@m0mus think we shoulnt accept null now (now = after a 1.0 documenting it is not accepted implicitly), a quick review on github (https://github.com/search?q=JsonbAdapter&type=Code) shows that it breaks apps. Question is: do we want to enable it for 1.1 or 2.0 with an @EnableNulls on the adapter? I'm -+0 on such a new feature (never saw it needed).

**Comment by m0mus** [comment]
@rmannibucau Lets enable it in the next version which is going to be 2.0.

**Comment by aguibert** [comment]
oops, I may have jumped the gun on the merge here. I saw what appeared to be a resolution on the issue but missed the most recent discussion in this PR.

IMO we should not have a new `@EnableNulls` config on the adapter, because this seems like a minor case that hasn't come up enough to warrant a dedicated annotation. Perhaps we could have the behavior key off of `JsonbConfig().withNullValues(true)` instead?

**Comment by rmannibucau** [comment]
@aguibert tempted to say we should just allow null values, validations belongs to constructor code, not to jsonb and JsonValue.NULL is not null but would fail today. Relaxing this constraint sounds like a low risk for me since apps relying on it will fail anyway and it enables to use the constructors/factories as intended (builders) so let's do it as a spec fix.

**Pull request merged**
